{
 "title": "Power Dashboard",
 "description": "Power Related Dashboard using prometheus",
 "tags": [
  "Linux",
  "NVIDIA GPU",
  "BMC",
  "CPU"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(powerall_uname_info_info,cluster)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(powerall_uname_info_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(powerall_uname_info_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Cluster Nodes",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_uname_info_info{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores in the whole Cluster",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cpu_utils{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NVGPUs",
   "type": "stat",
   "description": "NVGPU number",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvgpu_gpuinfo_info{cluster=\"$cluster\"})",
     "legendFormat": "{{cuda_v}}"
    }
   ]
  },
  {
   "title": "Total Avg Power(hwmon)",
   "type": "stat",
   "description": "Total Avg Power in Hwmon",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_hwmon_power_average_watt{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Power(BMC)",
   "type": "stat",
   "description": "Total Power in BMC",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Comsuption Rate",
   "type": "piechart",
   "description": "Power Comsuption Rate",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bmc_power_info{component=\"cpu\", cluster=\"$cluster\"}) / sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "CPU Power Rate"
    },
    {
     "expr": "sum(nvgpu_power{mode=\"usage\", cluster=\"$cluster\"}) / 1000 / sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "GPU Power Rate"
    },
    {
     "expr": "sum(bmc_power_info{component=\"fan\", cluster=\"$cluster\"}) / sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "Fan Power Rate"
    },
    {
     "expr": "sum(bmc_power_info{component=\"mem\", cluster=\"$cluster\"}) / sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "Mem Power Rate"
    },
    {
     "expr": "(sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"}) - sum(bmc_power_info{component=\"mem\", cluster=\"$cluster\"}) - sum(bmc_power_info{component=\"fan\", cluster=\"$cluster\"}) - (sum(nvgpu_power{mode=\"usage\", cluster=\"$cluster\"}) / 1000) - sum(bmc_power_info{component=\"cpu\", cluster=\"$cluster\"})) / sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "Others Power Rate"
    }
   ]
  },
  {
   "title": "Power Comsuption Trend",
   "type": "timeseries",
   "description": "Power Comsuption Trend",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(bmc_power_info{component=\"cpu\", cluster=\"$cluster\"}) / sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "CPU Power Rate"
    },
    {
     "expr": "sum(nvgpu_power{mode=\"usage\", cluster=\"$cluster\"}) / 1000 / sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "GPU Power Rate"
    },
    {
     "expr": "sum(bmc_power_info{component=\"fan\", cluster=\"$cluster\"}) / sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "Fan Power Rate"
    },
    {
     "expr": "sum(bmc_power_info{component=\"mem\", cluster=\"$cluster\"}) / sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "Mem Power Rate"
    },
    {
     "expr": "(sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"}) - sum(bmc_power_info{component=\"mem\", cluster=\"$cluster\"}) - sum(bmc_power_info{component=\"fan\", cluster=\"$cluster\"}) - sum(nvgpu_power{mode=\"usage\", cluster=\"$cluster\"}) / 1000 - sum(bmc_power_info{component=\"cpu\", cluster=\"$cluster\"})) / sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "Others Power Rate"
    }
   ]
  },
  {
   "title": "Total Fan Power",
   "type": "stat",
   "description": "Total Fan Power",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bmc_power_info{component=\"fan\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Power",
   "type": "stat",
   "description": "Total CPU Power",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bmc_power_info{component=\"cpu\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Mem Power",
   "type": "stat",
   "description": "Total Mem Power",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bmc_power_info{component=\"mem\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total NVGPU Power",
   "type": "stat",
   "description": "Total NVGPU Power",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvgpu_power{cluster=\"$cluster\", mode=\"usage\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total NVIDIA GPU Power",
   "type": "timeseries",
   "description": "The time-series for Power Usage of NVIDIA GPU",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "nvgpu_power{cluster=\"$cluster\", mode=\"usage\"}",
     "legendFormat": "{{ job }} GPU {{ index }}"
    },
    {
     "expr": "nvgpu_power{cluster=\"$cluster\", mode=\"enforce_limit\"}",
     "legendFormat": "{{ job }} GPU Enforced Limit: {{index}}"
    }
   ]
  },
  {
   "title": "Cluster GPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nvgpu_temp{cluster=\"$cluster\"}",
     "legendFormat": "{{job}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "Cluster hardware temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{cluster=\"$cluster\"} * on(chip, instance) group_left(chip_name) node_hwmon_chip_names{cluster=\"$cluster\"}",
     "legendFormat": "{{ job }} {{ chip_name }} {{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{cluster=\"$cluster\"} * on(chip, instance) group_left(chip_name) node_hwmon_chip_names{cluster=\"$cluster\"}",
     "legendFormat": "{{ job }} {{ chip_name }} {{ chip }} {{ sensor }} Critical"
    },
    {
     "expr": "node_hwmon_temp_max_celsius{cluster=\"$cluster\"} * on(chip, instance) group_left(chip_name) node_hwmon_chip_names{cluster=\"$cluster\"}",
     "legendFormat": "{{ job }} {{ chip_name }} {{ chip }} {{ sensor }} Max"
    }
   ]
  },
  {
   "title": "Cluster Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "bmc_fan_read{cluster=\"$cluster\"}",
     "legendFormat": "{{job}} {{name}}({{readingunits}})"
    }
   ]
  },
  {
   "title": "Cluster CPU Freqs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rotkhz" } },
   "targets": [
    {
     "expr": "cpu_freqs{mode=\"current\", cluster=\"$cluster\"}",
     "legendFormat": "{{ job }} CPU{{cpu}} freqs"
    }
   ]
  },
  {
   "title": "Cluster Loads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cpu_loadavg{cluster=\"$cluster\",m=\"1\"}",
     "legendFormat": "Node {{ job }} Load 1m"
    },
    {
     "expr": "cpu_loadavg{cluster=\"$cluster\",m=\"5\"}",
     "legendFormat": "Node {{ job }} Load 5m"
    },
    {
     "expr": "cpu_loadavg{cluster=\"$cluster\",m=\"15\"}",
     "legendFormat": "Node {{ job }} Load 15m"
    }
   ]
  },
  {
   "title": "Cluster I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{cluster=\"$cluster\"} [$__rate_interval])",
     "legendFormat": "Node {{ job }} {{device}}"
    }
   ]
  },
  {
   "title": "Cluster HWMON Power",
   "type": "timeseries",
   "description": "Cluster HWMON Power",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(node_hwmon_power_average_watt{cluster=\"$cluster\"})",
     "legendFormat": "Cluster Hwmon Power"
    }
   ]
  },
  {
   "title": "Cluster Power in BMC",
   "type": "timeseries",
   "description": "Cluster Power in BMC",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(bmc_power_info{component=\"total\", cluster=\"$cluster\"})",
     "legendFormat": "Cluster Power"
    }
   ]
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cpu_utils{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NVGPU Power",
   "type": "stat",
   "description": "NVGPU Power",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvgpu_power{instance=\"$node\",job=\"$job\",mode=\"usage\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Power(hwmon)",
   "type": "stat",
   "description": "Average Hwmon Watt",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_hwmon_power_average_watt{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "stat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_loadavg{instance=\"$node\",job=\"$job\",m=\"1\"}",
     "legendFormat": "1m avg"
    },
    {
     "expr": "cpu_loadavg{instance=\"$node\",job=\"$job\",m=\"5\"}",
     "legendFormat": "5m avg"
    },
    {
     "expr": "cpu_loadavg{instance=\"$node\",job=\"$job\",m=\"15\"}",
     "legendFormat": "15m avg"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Slab_bytes{instance=\"$node\",job=\"$job\"} - node_memory_PageTables_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapCached_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cpu_loadavg{instance=\"$node\",job=\"$job\",m=\"1\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "cpu_loadavg{instance=\"$node\",job=\"$job\",m=\"5\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "cpu_loadavg{instance=\"$node\",job=\"$job\",m=\"15\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(cpu_seconds_total{instance=\"$node\",job=\"$job\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval]) - avg_over_time(node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval])) / (avg_over_time(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval]) )) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by(instance) (irate(cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"nice\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by(instance) (irate(cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by(instance) (irate(cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"softirq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by(instance) (irate(cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"steal\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by(instance) (irate(cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Processes Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_blocked{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    },
    {
     "expr": "node_procs_running{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Processes in runnable state"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Process schedule stats Running / Waiting",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Processes  Forks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_forks_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Processes forks second"
    }
   ]
  },
  { "title": "BMC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Machine Power in BMC",
   "type": "timeseries",
   "description": "Machine Power in BMC",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "bmc_power_info{job=\"$job\", component=\"total\"}",
     "legendFormat": "{{job}} Total Power"
    },
    {
     "expr": "bmc_power_info{job=\"$job\", component=\"fan\"}",
     "legendFormat": "{{job}} Fan Power"
    },
    {
     "expr": "bmc_power_info{job=\"$job\", component=\"cpu\"}",
     "legendFormat": "{{job}} CPU Power"
    },
    {
     "expr": "bmc_power_info{job=\"$job\", component=\"mem\"}",
     "legendFormat": "{{job}} Memory Power"
    }
   ]
  },
  {
   "title": "Machine Info",
   "type": "stat",
   "description": "Machine Info",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bmc_machine_info_info{job=\"$job\"}",
     "legendFormat": "{{manufacturer}} {{model}}"
    }
   ]
  },
  {
   "title": "Fan Speed in BMC",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bmc_fan_read{job=\"$job\"}",
     "legendFormat": "{{job}} {{name}}({{readingunits}})"
    }
   ]
  },
  { "title": "HWMON", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "HWMON In Volts",
   "type": "timeseries",
   "description": "HWMON Input Volts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "node_hwmon_in_volts{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "chip: {{chip}} / sensor: {{sensor}}"
    }
   ]
  },
  {
   "title": "HWMON Fan rpm",
   "type": "timeseries",
   "description": "HWMON Fan rpm",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "chip: {{chip}} / sensor: {{sensor}}"
    }
   ]
  },
  {
   "title": "HWMON Power Avg Watt",
   "type": "timeseries",
   "description": "HWMON Power Avg Watt",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "chip: {{chip}} / sensor: {{sensor}}"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\",job=\"$job\"} * on(chip) group_left(chip_name) node_hwmon_chip_names{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip_name }} {{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"$node\",job=\"$job\"} * on(chip) group_left(chip_name) node_hwmon_chip_names{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip_name }} {{ chip }} {{ sensor }} Critical"
    },
    {
     "expr": "node_hwmon_temp_max_celsius{instance=\"$node\",job=\"$job\"} * on(chip) group_left(chip_name) node_hwmon_chip_names{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip_name }} {{ chip }} {{ sensor }} Max"
    }
   ]
  },
  { "title": "Infiniband", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Infiniband HCA Card Info",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_infiniband_info{job=\"$job\"}",
     "legendFormat": "{{device}} {{hca_type}}"
    }
   ]
  },
  {
   "title": "Infiniband Firmware Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_infiniband_info{job=\"$job\"}",
     "legendFormat": "{{firmware_version}}"
    }
   ]
  },
  {
   "title": "Infiniband HCA Card stat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_infiniband_state_id{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "CPU Frequency Scaling",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "rotkhz" } },
   "targets": [
    {
     "expr": "cpu_freqs{job=\"$job\", mode=\"current\"}",
     "legendFormat": "CPU {{ cpu }}"
    },
    {
     "expr": "avg(cpu_freqs{job=\"$job\", mode=\"max\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(cpu_freqs{job=\"$job\", mode=\"min\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "CPU Utils",
   "type": "timeseries",
   "description": "cpu utils",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_utils{job=\"$job\"}",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  { "title": "GPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "CUDA Version",
   "type": "stat",
   "description": "CUDA Version",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvgpu_sysinfo_info{job=\"$job\"}",
     "legendFormat": "{{cuda_v}}"
    }
   ]
  },
  {
   "title": "NVML Version",
   "type": "stat",
   "description": "NVML Version",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvgpu_sysinfo_info{job=\"$job\"}",
     "legendFormat": "{{nvml_v}}"
    }
   ]
  },
  {
   "title": "NVIDIA Driver Version",
   "type": "stat",
   "description": "NVIDIA Driver Version",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvgpu_sysinfo_info{job=\"$job\"}",
     "legendFormat": "{{driver_v}}"
    }
   ]
  },
  {
   "title": "GPU Bus Type",
   "type": "stat",
   "description": "GPU Bus Type",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvgpu_gpuinfo_info{job=\"$job\"}",
     "legendFormat": "{{index}}:{{bus_type}}"
    }
   ]
  },
  {
   "title": "GPU Compute Mode",
   "type": "stat",
   "description": "GPU Compute Mode",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvgpu_compute_mode_info{job=\"$job\"}",
     "legendFormat": "{{index}}:{{mode}}"
    }
   ]
  },
  {
   "title": "GPU Persistence Mode",
   "type": "stat",
   "description": "GPU Persistence Mode",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvgpu_persis_mode_info{job=\"$job\"}",
     "legendFormat": "{{index}}:{{mode}}"
    }
   ]
  },
  {
   "title": "GPU Fan Speed Limit",
   "type": "stat",
   "description": "GPU Min/Max Fan Speed",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvgpu_min_fan_speed{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nvgpu_max_fan_speed{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NVIDIA GPU Temperature",
   "type": "timeseries",
   "description": "The time-series for temperature of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nvgpu_temp{job=\"$job\"}",
     "legendFormat": "GPU: {{index}}"
    }
   ]
  },
  {
   "title": "GPU UUID",
   "type": "stat",
   "description": "GPU UUID",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvgpu_gpuinfo_info{job=\"$job\"}",
     "legendFormat": "{{index}}:{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Name",
   "type": "stat",
   "description": "GPU Name",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvgpu_gpuinfo_info{job=\"$job\"}",
     "legendFormat": "{{index}}:{{name}}"
    }
   ]
  },
  {
   "title": "NVIDIA GPU Clock",
   "type": "timeseries",
   "description": "The time-series for clock of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "nvgpu_clk{job=\"$job\"}",
     "legendFormat": "GPU: {{index}} / Type: {{type}} / ID: {{id}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "description": "GPU Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvgpu_util{job=\"$job\"}",
     "legendFormat": "GPU{{index}}:{{type}}"
    }
   ]
  },
  {
   "title": "NVIDIA GPU Power",
   "type": "timeseries",
   "description": "The time-series for Power Usage of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "nvgpu_power{job=\"$job\", mode=\"usage\"}",
     "legendFormat": "GPU Power Usage: {{index}}"
    },
    {
     "expr": "nvgpu_power{job=\"$job\", mode=\"enforce_limit\"}",
     "legendFormat": "GPU Enforced Limit: {{index}}"
    },
    {
     "expr": "nvgpu_power{job=\"$job\", mode=\"max\"}",
     "legendFormat": "GPU Max: {{index}}"
    },
    {
     "expr": "nvgpu_power{job=\"$job\", mode=\"min\"}",
     "legendFormat": "GPU Min: {{index}}"
    }
   ]
  },
  {
   "title": "NVIDIA GPU Memory Usage",
   "type": "timeseries",
   "description": "The time-series for Memory Usage of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nvgpu_mem{job=\"$job\",mode=\"total\"}",
     "legendFormat": "GPU MemTotal: {{index}}"
    },
    {
     "expr": "nvgpu_mem{job=\"$job\", mode=\"used\"}",
     "legendFormat": "GPU MemUsed: {{index}} "
    },
    {
     "expr": "nvgpu_mem{job=\"$job\", mode=\"free\"}",
     "legendFormat": "GPU MemFree: {{index}}"
    }
   ]
  },
  {
   "title": "NVIDIA GPU App Clock",
   "type": "timeseries",
   "description": "The time-series for applications clock of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "nvgpu_appclk{job=\"$job\"}",
     "legendFormat": "GPU: {{index}} / Type: {{type}}"
    }
   ]
  },
  {
   "title": "NVIDIA GPU Fanspeed",
   "type": "timeseries",
   "description": "The time-series for Fan Speed of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "nvgpu_fan_speed{job=\"$job\", mode=\"current\"}",
     "legendFormat": "GPU: {{index}} Fan {{fan}} Current"
    },
    {
     "expr": "nvgpu_fan_speed{job=\"$job\", mode=\"min\"}",
     "legendFormat": "GPU: {{index}} Fan {{fan}} Min"
    },
    {
     "expr": "nvgpu_fan_speed{job=\"$job\", mode=\"max\"}",
     "legendFormat": "GPU: {{index}} Fan {{fan}} Max"
    }
   ]
  },
  { "title": "PowerAll Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "Power Exporter Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{collector}} - Scrape duration"
    }
   ]
  },
  {
   "title": "Power Exporter Scrape",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_scrape_collector_success{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{collector}} - Scrape success"
    },
    {
     "expr": "node_textfile_scrape_error{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{collector}} - Scrape textfile error (1 = true)"
    }
   ]
  }
 ]
}