apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    access: proxy
    url: http://powerall-prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      timeInterval: 5s
